export const mockJobs = [
    {
        id: 1,
        projectName: "Coffee Campaign",
        projectIcon: "J",
        projectColor: "bg-indigo-500",
        professionalName: "Jordan Rivera",
        professionalAvatar: null,
        professionalInitial: "A",
        professionalColor: "bg-amber-400",
        clientName: "Jordan Rivera",
        stage: "In Progress",
        deadline: "2024-01-15",
    },
    {
        id: 2,
        projectName: "Coffee Campaign",
        projectIcon: "J",
        projectColor: "bg-indigo-500",
        professionalName: "Jordan Rivera",
        professionalAvatar: null,
        professionalInitial: "A",
        professionalColor: "bg-amber-400",
        clientName: "Jordan Rivera",
        stage: "Completed",
        deadline: "2024-02-10",
    },
    {
        id: 3,
        projectName: "Coffee Campaign",
        projectIcon: "J",
        projectColor: "bg-indigo-500",
        professionalName: "Jordan Rivera",
        professionalAvatar: null,
        professionalInitial: "A",
        professionalColor: "bg-amber-400",
        clientName: "Jordan Rivera",
        stage: "Pending",
        deadline: "2024-03-05",
    },
    {
        id: 4,
        projectName: "Coffee Campaign",
        projectIcon: "J",
        projectColor: "bg-indigo-500",
        professionalName: "Jordan Rivera",
        professionalAvatar: null,
        professionalInitial: "A",
        professionalColor: "bg-amber-400",
        clientName: "Jordan Rivera",
        stage: "In Progress",
        deadline: "2024-01-20",
    },
    {
        id: 5,
        projectName: "Coffee Campaign",
        projectIcon: "J",
        projectColor: "bg-indigo-500",
        professionalName: "Jordan Rivera",
        professionalAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150",
        professionalInitial: "",
        professionalColor: "",
        clientName: "Jordan Rivera",
        stage: "Completed",
        deadline: "2024-04-01",
    },
    {
        id: 6,
        projectName: "Coffee Campaign",
        projectIcon: "J",
        projectColor: "bg-indigo-500",
        professionalName: "Jordan Rivera",
        professionalAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150",
        professionalInitial: "",
        professionalColor: "",
        clientName: "Jordan Rivera",
        stage: "Pending",
        deadline: "2023-12-10",
    },
    {
        id: 7,
        projectName: "Coffee Campaign",
        projectIcon: "J",
        projectColor: "bg-indigo-500",
        professionalName: "Jordan Rivera",
        professionalAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150",
        professionalInitial: "",
        professionalColor: "",
        clientName: "Jordan Rivera",
        stage: "Completed",
        deadline: "2024-05-15",
    },
    {
        id: 8,
        projectName: "Coffee Campaign",
        projectIcon: "J",
        projectColor: "bg-indigo-500",
        professionalName: "Jordan Rivera",
        professionalAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150",
        professionalInitial: "",
        professionalColor: "",
        clientName: "Jordan Rivera",
        stage: "In Progress",
        deadline: "2024-02-28",
    },
];
